#! /bin/bash

if [ $# -eq 0 ]; then
	echo "Usage: addModule [moduleName]"
	exit 1
fi

mkdir www/public/$1
mkdir www/private/$1

mkdir www/public/$1/css
mkdir www/public/$1/js
mkdir www/public/$1/images

mkdir www/private/$1/css
mkdir www/private/$1/js
mkdir www/private/$1/images

mkdir views/$1
mkdir app/$1

echo "Created module $1."
